-- Simplified Long Video Studio
-- Flow: create project -> pick ideas from All Ideas -> manage a recording checklist.

create table if not exists public.long_video_project_ideas (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.long_video_projects(id) on delete cascade,
  detail_id bigint not null references public.details(id) on delete cascade,
  position integer not null default 0,
  capture_status text not null default 'to_record'
    check (capture_status in ('to_record','recorded','retake','approved')),
  recording_notes text,
  file_location text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (project_id, detail_id)
);

create index if not exists long_video_project_ideas_project_position_idx
  on public.long_video_project_ideas(project_id, position);
create index if not exists long_video_project_ideas_capture_status_idx
  on public.long_video_project_ideas(project_id, capture_status);

drop trigger if exists set_long_video_project_ideas_updated_at on public.long_video_project_ideas;
create trigger set_long_video_project_ideas_updated_at
before update on public.long_video_project_ideas
for each row execute function public.set_updated_at();

-- Preserve ideas already added through the earlier chapter-based workspace.
insert into public.long_video_project_ideas(project_id, detail_id, position)
select project_id, detail_id, (row_number() over (partition by project_id order by chapter_position, idea_position, detail_id) - 1)::integer
from (
  select distinct on (chapter.project_id, chapter_idea.detail_id)
    chapter.project_id,
    chapter_idea.detail_id,
    chapter.position as chapter_position,
    chapter_idea.position as idea_position
  from public.long_video_chapters chapter
  join public.long_video_chapter_ideas chapter_idea on chapter_idea.chapter_id = chapter.id
  order by chapter.project_id, chapter_idea.detail_id, chapter.position, chapter_idea.position
) migrated
on conflict (project_id, detail_id) do nothing;

alter table public.long_video_project_ideas enable row level security;
revoke all on public.long_video_project_ideas from anon, authenticated;
