-- Phase 1 + 2: Audience Requests and Long Video Studio.
-- Run once in Supabase SQL Editor, then add SUPABASE_SERVICE_ROLE_KEY to the server environment.

create table if not exists public.long_video_projects (
  id bigint generated by default as identity primary key,
  title text not null,
  core_idea text,
  viewer_promise text,
  target_duration_minutes integer not null default 10 check (target_duration_minutes > 0),
  target_audience text,
  thumbnail_notes text,
  status text not null default 'planning' check (status in ('planning','writing','recording','editing','ready','published')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.long_video_chapters (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.long_video_projects(id) on delete cascade,
  title text not null,
  position integer not null default 0,
  script text not null default '',
  status text not null default 'draft' check (status in ('draft','ready','recorded')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.long_video_chapter_ideas (
  id bigint generated by default as identity primary key,
  chapter_id bigint not null references public.long_video_chapters(id) on delete cascade,
  detail_id bigint not null references public.details(id) on delete cascade,
  position integer not null default 0,
  created_at timestamptz not null default now(),
  unique (chapter_id, detail_id)
);

create table if not exists public.audience_requests (
  id bigint generated by default as identity primary key,
  comment_text text not null,
  commenter_name text,
  source_url text,
  game_id bigint references public.games(id) on delete set null,
  notes text,
  content_type text not null default 'undecided' check (content_type in ('short','long','undecided')),
  status text not null default 'inbox' check (status in ('inbox','planned','in_progress','published','replied')),
  promised boolean not null default false,
  published_url text,
  linked_idea_id bigint references public.details(id) on delete set null,
  linked_short_project_id bigint references public.scripts(id) on delete set null,
  linked_long_project_id bigint references public.long_video_projects(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists audience_requests_source_url_unique
  on public.audience_requests (source_url)
  where source_url is not null and btrim(source_url) <> '';
create index if not exists audience_requests_status_idx on public.audience_requests (status, created_at desc);
create index if not exists audience_requests_game_idx on public.audience_requests (game_id);
create index if not exists long_video_projects_status_idx on public.long_video_projects (status, updated_at desc);
create index if not exists long_video_chapters_project_position_idx on public.long_video_chapters (project_id, position);
create index if not exists long_video_chapter_ideas_position_idx on public.long_video_chapter_ideas (chapter_id, position);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_audience_requests_updated_at on public.audience_requests;
create trigger set_audience_requests_updated_at before update on public.audience_requests
for each row execute function public.set_updated_at();

drop trigger if exists set_long_video_projects_updated_at on public.long_video_projects;
create trigger set_long_video_projects_updated_at before update on public.long_video_projects
for each row execute function public.set_updated_at();

drop trigger if exists set_long_video_chapters_updated_at on public.long_video_chapters;
create trigger set_long_video_chapters_updated_at before update on public.long_video_chapters
for each row execute function public.set_updated_at();

-- Save a complete workspace in one database transaction.
create or replace function public.save_long_video_workspace(
  p_project_id bigint,
  p_project jsonb,
  p_chapters jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  chapter_json jsonb;
  idea_json jsonb;
  chapter_id_value bigint;
  kept_chapter_ids bigint[] := array[]::bigint[];
  chapter_position integer := 0;
  idea_position integer;
begin
  update public.long_video_projects
  set
    title = coalesce(nullif(btrim(p_project->>'title'), ''), title),
    core_idea = nullif(btrim(p_project->>'core_idea'), ''),
    viewer_promise = nullif(btrim(p_project->>'viewer_promise'), ''),
    target_duration_minutes = greatest(1, coalesce(nullif(p_project->>'target_duration_minutes','')::integer, target_duration_minutes)),
    target_audience = nullif(btrim(p_project->>'target_audience'), ''),
    thumbnail_notes = nullif(btrim(p_project->>'thumbnail_notes'), ''),
    status = case when p_project->>'status' in ('planning','writing','recording','editing','ready','published') then p_project->>'status' else status end,
    updated_at = now()
  where id = p_project_id;

  for chapter_json in select value from jsonb_array_elements(coalesce(p_chapters, '[]'::jsonb))
  loop
    if nullif(chapter_json->>'id', '') is null then
      insert into public.long_video_chapters(project_id, title, position, script, status)
      values (
        p_project_id,
        coalesce(nullif(btrim(chapter_json->>'title'), ''), 'Untitled chapter'),
        chapter_position,
        coalesce(chapter_json->>'script', ''),
        case when chapter_json->>'status' in ('draft','ready','recorded') then chapter_json->>'status' else 'draft' end
      ) returning id into chapter_id_value;
    else
      chapter_id_value := (chapter_json->>'id')::bigint;
      update public.long_video_chapters
      set
        title = coalesce(nullif(btrim(chapter_json->>'title'), ''), title),
        position = chapter_position,
        script = coalesce(chapter_json->>'script', ''),
        status = case when chapter_json->>'status' in ('draft','ready','recorded') then chapter_json->>'status' else status end,
        updated_at = now()
      where id = chapter_id_value and project_id = p_project_id;
      if not found then raise exception 'Chapter % does not belong to project %', chapter_id_value, p_project_id; end if;
    end if;

    kept_chapter_ids := array_append(kept_chapter_ids, chapter_id_value);
    delete from public.long_video_chapter_ideas where chapter_id = chapter_id_value;
    idea_position := 0;
    for idea_json in select value from jsonb_array_elements(coalesce(chapter_json->'ideas', '[]'::jsonb))
    loop
      insert into public.long_video_chapter_ideas(chapter_id, detail_id, position)
      values (chapter_id_value, (idea_json->>'detail_id')::bigint, idea_position)
      on conflict (chapter_id, detail_id) do update set position = excluded.position;
      idea_position := idea_position + 1;
    end loop;
    chapter_position := chapter_position + 1;
  end loop;

  delete from public.long_video_chapters
  where project_id = p_project_id
    and not (id = any(kept_chapter_ids));
end;
$$;

-- These tables are private. Browser anon/authenticated clients receive no direct access.
alter table public.audience_requests enable row level security;
alter table public.long_video_projects enable row level security;
alter table public.long_video_chapters enable row level security;
alter table public.long_video_chapter_ideas enable row level security;

revoke all on public.audience_requests from anon, authenticated;
revoke all on public.long_video_projects from anon, authenticated;
revoke all on public.long_video_chapters from anon, authenticated;
revoke all on public.long_video_chapter_ideas from anon, authenticated;
revoke execute on function public.save_long_video_workspace(bigint, jsonb, jsonb) from public, anon, authenticated;
grant execute on function public.save_long_video_workspace(bigint, jsonb, jsonb) to service_role;
